# Generated by Django 5.0.3 on 2024-03-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DoctorApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
