# Generated by Django 5.0.3 on 2024-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DoctorApp", "0003_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.IntegerField(
                choices=[(2, "doc"), (3, "User"), (1, "admin")], default=3
            ),
        ),
    ]
