# Generated by Django 5.0.3 on 2024-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DoctorApp", "0004_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "admin"), (2, "doc"), (3, "User")], default=3
            ),
        ),
    ]
