# Generated by Django 5.0.3 on 2024-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DoctorApp", "0005_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.IntegerField(
                choices=[(3, "User"), (1, "admin"), (2, "doc")], default=3
            ),
        ),
    ]
