# Generated by Django 5.0.3 on 2024-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DoctorApp", "0010_alter_users_options_alter_users_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.IntegerField(choices=[(2, "doc"), (1, "admin")]),
        ),
    ]
