# Generated by Django 5.0.3 on 2024-04-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DoctorApp", "0011_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.IntegerField(choices=[(1, "admin"), (2, "doc")]),
        ),
    ]
